# Generated by Django 3.2.7 on 2021-11-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(choices=[('SL', 'Select Event'), ('Mosaic', 'Mosaic'), ('Spybits', 'Spybits'), ('Digisim', 'Digisim'), ('Continuum', 'Continuum'), ('Cassandra', 'Cassandra'), ('Commnet', 'Commnet'), ('Funckit', 'Funckit'), ('X-IoT-A', 'X-IoT-A'), ('I-Chip', 'I-Chip')], default='SL', max_length=20)),
                ('members_from_1st_year', models.IntegerField()),
                ('members_after_1st_year', models.IntegerField()),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udyam_API.event')),
            ],
        ),
    ]
