# Generated by Django 3.2.7 on 2021-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_API', '0003_auto_20211130_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number_of_members',
            field=models.CharField(choices=[('SL', 'Select No. of Members'), ('1', '1'), ('2', '2'), ('3,', '3')], default='SL', max_length=2),
        ),
    ]
