# Generated by Django 3.2.7 on 2021-12-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_API', '0004_team_number_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='number_of_members',
        ),
    ]
