# Generated by Django 3.2.7 on 2021-12-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_API', '0006_team_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='submission',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
