# Generated by Django 3.2.7 on 2021-10-03 09:58

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='False', max_length=200, null='False')),
                ('email', models.EmailField(blank='False', max_length=200, null='False')),
                ('college_name', models.CharField(blank='False', max_length=200, null='False')),
                ('year', models.CharField(blank='False', choices=[('ONE', '1st year'), ('TWO', '2nd year'), ('THREE', '3rd year'), ('FOUR', '4th year')], max_length=20, null='False')),
                ('gender', models.CharField(blank='False', choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=20, null='False')),
                ('mobile_no', models.CharField(blank='False', max_length=10, null='False', validators=[django.core.validators.MinLengthValidator(10), authentication.models.validate_phone_number])),
                ('password', models.CharField(blank='False', max_length=20, null='False', validators=[django.core.validators.MinLengthValidator(8), authentication.models.validate_password])),
                ('confirm_password', models.CharField(blank='False', max_length=20, null='False', validators=[django.core.validators.MinLengthValidator(8), authentication.models.validate_password])),
                ('user_referral_code', models.CharField(blank='False', max_length=6, null='False')),
                ('referral_code', models.CharField(blank='True', max_length=6, null='True')),
            ],
        ),
    ]
