# Generated by Django 3.2.7 on 2021-11-19 18:59

import addons.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), addons.models.validate_phone_number])),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
